# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'mbox-agent:$(build.buildId)'
  imageNameLast: 'mbox-agent:latest'
  username: 'mboxcontainers'
  dockerId: 'mboxcontainers.azurecr.io'
  pswd: 'eJuZUdKY53eqUBBKegB0pC8Hl8U+w0IL'

steps:
- script: |
    docker run --rm --privileged multiarch/qemu-user-static:register --reset
    docker login -u $(username) -p $(pswd) $(dockerId)
    docker build -t $(dockerId)/$(imageName) -t $(dockerId)/$(imageNameLast) .
    docker push $(dockerId)/$(imageName)